//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int Point { get; set; }
        public string UrlImage { get; set; }
        public string Description { get; set; }
        public int CreateUserID { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IsActive { get; set; }
        public Nullable<int> TelecomType { get; set; }
    
        public virtual User User { get; set; }
    }
}
