//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersPointHistory
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public double Point { get; set; }
        public int Type { get; set; }
        public string AddPointCode { get; set; }
        public int TypeAdd { get; set; }
        public System.DateTime CraeteDate { get; set; }
        public int IsActive { get; set; }
        public string Comment { get; set; }
        public string Title { get; set; }
        public double Balance { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> UserSendID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
