//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TichDiemTrieuDo : DbContext
    {
        public TichDiemTrieuDo()
            : base("name=TichDiemTrieuDo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<AppVersion> AppVersions { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<CategoryNew> CategoryNews { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerBank> CustomerBanks { get; set; }
        public virtual DbSet<CustomerImage> CustomerImages { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Gift> Gifts { get; set; }
        public virtual DbSet<GroupItem> GroupItems { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<MembersPointHistory> MembersPointHistories { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotifiWeb> NotifiWebs { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Ranking> Rankings { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<ShopImage> ShopImages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Warranty> Warranties { get; set; }
        public virtual DbSet<WarrantyCard> WarrantyCards { get; set; }
    }
}
