//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MembersPointHistories = new HashSet<MembersPointHistory>();
        }
    
        public int ID { get; set; }
        public int BatchID { get; set; }
        public Nullable<int> CustomerActiveID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IsActive { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersPointHistory> MembersPointHistories { get; set; }
    }
}
