//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int ID { get; set; }
        public string RankName { get; set; }
        public string Descriptions { get; set; }
        public System.DateTime CraeteDate { get; set; }
        public int IsActive { get; set; }
        public Nullable<int> MinPoint { get; set; }
        public Nullable<int> MaxPoint { get; set; }
        public Nullable<int> Level { get; set; }
    }
}
