//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warranty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warranty()
        {
            this.WarrantyCards = new HashSet<WarrantyCard>();
        }
    
        public int ID { get; set; }
        public int CreateUserID { get; set; }
        public string WarrantyCode { get; set; }
        public int QTY { get; set; }
        public int Point { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IsActive { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarrantyCard> WarrantyCards { get; set; }
    }
}
